// Ten layout oplecie wszystkie strony i inne layouty
// musi się znajdować w app directory i jest wymagany
// Po migracji z next 12 ten layout zastępuje _app.js i _document.js
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";
import "react-loading-skeleton/dist/skeleton.css";

const inter = Inter({ subsets: ["latin"] });

// w ten sposób definiuj metadane strony
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar />
        <h1>I am root layout</h1>
        {children}
      </body>
    </html>
  );
}
